version: '3.7'

services:

  rancher-server:
    image: rancher/rancher:latest
    privileged: true
    restart: unless-stopped
    container_name: rancher-server
    volumes:
      - /opt/rancher:/var/lib/rancher

  nginx:
    image: nginx:1.11
    restart: unless-stopped
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /root/certs:/etc/nginx/ssl
      - /root/nginx-conf/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - rancher-server
