[entrypoints]
  [entrypoints.http]
    address = ":80"
  [entrypoints.https]
    address = ":443"

[api]
  dashboard = true
  insecure = true

[providers]
  [providers.docker]
    swarmMode = false
    network = "traefik"
    exposedbydefault = false
  
  [providers.file]
    filename = "/etc/traefik/dyn.toml"
    watch = true
